-- AlterTable
ALTER TABLE "public"."CLIENTS" ADD COLUMN     "PS_DCITY" TEXT,
ADD COLUMN     "PS_DSTATE" TEXT,
ADD COLUMN     "PS_OGIVN" TEXT,
ADD COLUMN     "PS_OSURN" TEXT,
ADD COLUMN     "PS_QST1" TEXT,
ADD COLUMN     "PS_TELCOD" TEXT;
