-- CreateTable
CREATE TABLE "public"."CLIENTS" (
    "ID_CLIENT" BIGSERIAL NOT NULL,
    "PS_SURNAME" TEXT,
    "PS_GIVNAM" TEXT,
    "PS_SEX" TEXT,
    "PS_EMAIL" TEXT,
    "PS_DBIRTH" DATE,
    "PS_COUNTRY" TEXT,
    "PS_HOLD" TEXT,
    "PS_OCOUNTRY" TEXT,
    "PS_RESIDENT" TEXT,
    "PS_RCOUNTRY" TEXT,
    "PS_HOCCOUNTRY" TEXT,
    "PS_PASSHOLD" TEXT,
    "PS_IDENTITY" TEXT,
    "PS_SECNUMBER" TEXT,
    "PS_TAXNUMBER" TEXT,

    CONSTRAINT "CLIENTS_pkey" PRIMARY KEY ("ID_CLIENT")
);
