-- CreateTable
CREATE TABLE "public"."TRAVEL_INFO" (
    "ID_TRAVEL" BIGSERIAL NOT NULL,
    "ID_CLIENT" BIGINT,
    "PTI_BEEN" TEXT,
    "PTI_DATE1" DATE,
    "PTI_LEN1" TEXT,
    "PTI_DATE2" DATE,
    "PTI_LEN2" TEXT,
    "PTI_DATE3" DATE,
    "PTI_LEN3" TEXT,
    "PTI_DATE4" DATE,
    "PTI_LEN4" TEXT,
    "PTI_DATE5" DATE,
    "PTI_LEN5" TEXT,
    "PTI_HOLDRIVER" CHAR(1),
    "PTI_LICENSE" TEXT,
    "PTI_SLICENSE" TEXT,
    "PTI_ISSUEDV" CHAR(1),
    "PTI_DATEISSUED" DATE,
    "PTI_DATEXPIRED" DATE,
    "PTI_REDNUMBER" TEXT,
    "PTI_SAMEVISA" CHAR(1),
    "PTI_SAMECNT" CHAR(1),
    "PTI_TENPRINTED" CHAR(1),
    "PTI_LOST" TEXT,
    "PTI_QST1" TEXT,
    "PTI_RST1" TEXT,
    "PTI_QST2" CHAR(1),
    "PTI_RST2" TEXT,
    "PTI_QST3" CHAR(1),
    "PTI_RST3" TEXT,
    "PTI_QST4" CHAR(1),
    "PTI_RST4" TEXT,
    "PTI_QST5" CHAR(1),
    "PTI_RST5" TEXT,

    CONSTRAINT "TRAVEL_INFO_pkey" PRIMARY KEY ("ID_TRAVEL")
);

-- CreateTable
CREATE TABLE "public"."ADDRESS" (
    "ID_ADDRESS" BIGSERIAL NOT NULL,
    "ID_CLIENT" BIGINT,
    "ADD_ADD1" TEXT,
    "ADD_ADD2" TEXT,
    "ADD_CITY" TEXT,
    "ADD_STATE" TEXT,
    "ADD_POSTAL" TEXT,
    "ADD_COUNTRY" TEXT,
    "ADD_MAILING" TEXT,
    "ADD_SAMEADD" TEXT,
    "ADD_MADD1" TEXT,
    "ADD_MADD2" TEXT,
    "ADD_MCITY" TEXT,
    "ADD_MSTATE" TEXT,
    "ADD_MPOSTAL" TEXT,
    "ADD_MCOUNTRY" TEXT,
    "ADD_PHONE1" TEXT,
    "ADD_PHONE2" TEXT,
    "ADD_WPHONE" TEXT,
    "ADD_ADDPHONE" TEXT,
    "ADD_PHONE3" TEXT,
    "ADD_MAIL1" TEXT,
    "ADD_ADDMAIL" TEXT,
    "ADD_MAIL2" TEXT,

    CONSTRAINT "ADDRESS_pkey" PRIMARY KEY ("ID_ADDRESS")
);

-- CreateTable
CREATE TABLE "public"."PASSPORT" (
    "ID_PASSPORT" BIGSERIAL NOT NULL,
    "ID_CLIENT" BIGINT,
    "PI_TYPE" TEXT,
    "PI_NUMBER" TEXT,
    "PI_BOOKN" TEXT,
    "PI_COUNTRY" TEXT,
    "PI_PLCISSUED" TEXT,
    "PI_CITY" TEXT,
    "PI_STATE" TEXT,
    "PI_COUNTRYR" TEXT,
    "PI_ISSUED" DATE,
    "PI_EXPIRED" DATE,
    "PI_LOST" TEXT,
    "PI_LNUMBER" TEXT,
    "PI_LCOUNTRY" TEXT,
    "PI_LEXP" DATE,

    CONSTRAINT "PASSPORT_pkey" PRIMARY KEY ("ID_PASSPORT")
);

-- CreateTable
CREATE TABLE "public"."FAMILY" (
    "ID_FAMILY" BIGSERIAL NOT NULL,
    "ID_CLIENT" BIGINT,
    "FLY_FSUR" TEXT,
    "FLY_FGIV" TEXT,
    "FLY_FDATE" DATE,
    "FLY_FUS" TEXT,
    "FLY_MSUR" TEXT,
    "FLY_MGIV" TEXT,
    "FLY_MDATE" DATE,
    "FLY_MUS" TEXT,
    "FLY_QST1" TEXT,
    "FLY_R1SUR" TEXT,
    "FLY_R1GIV" TEXT,
    "FLY_R1REL" TEXT,
    "FLY_R1STAT" TEXT,
    "FLY_R2SUR" TEXT,
    "FLY_R2GIV" TEXT,
    "FLY_R2REL" TEXT,
    "FLY_R2STAT" TEXT,
    "FLY_QST2" TEXT,
    "FLY_O1SUR" TEXT,
    "FLY_O1GIV" TEXT,
    "FLY_O1DATE" DATE,
    "FLY_O1CNT" TEXT,
    "FLY_O1CITY" TEXT,
    "FLY_O1REG" TEXT,
    "FLY_O1ADD1" TEXT,
    "FLY_O1ADD2" TEXT,
    "FLY_O1ACITY" TEXT,
    "FLY_O1ASTATE" TEXT,
    "FLY_O1POSTAL" TEXT,
    "FLY_O1PHONE" TEXT,
    "FLY_FSSUR" TEXT,
    "FLY_FSGIV" TEXT,
    "FLY_FSDATE" DATE,
    "FLY_FCNT" TEXT,
    "FLY_FPOB" TEXT,
    "FLY_FDATEM" DATE,
    "FLY_FDATEE" DATE,
    "FLY_FTCNT" TEXT,

    CONSTRAINT "FAMILY_pkey" PRIMARY KEY ("ID_FAMILY")
);

-- CreateTable
CREATE TABLE "public"."PRESS_WORK" (
    "ID_PRESS_WORK" BIGSERIAL NOT NULL,
    "ID_CLIENT" BIGINT,
    "PW_PROCP" TEXT,
    "PW_PENAM" TEXT,
    "PW_STADD1" TEXT,
    "PW_STADD2" TEXT,
    "PW_CITY" TEXT,
    "PW_STATE" TEXT,
    "PW_CNTRY" TEXT,
    "PW_TEL" TEXT,
    "PW_SRTDAT" DATE,
    "PW_ZIP" TEXT,
    "PW_INC" TEXT,
    "PW_DUT" TEXT,

    CONSTRAINT "PRESS_WORK_pkey" PRIMARY KEY ("ID_PRESS_WORK")
);

-- CreateTable
CREATE TABLE "public"."PREV_WORK" (
    "ID_PREV_WORK" BIGSERIAL NOT NULL,
    "ID_CLIENT" BIGINT,
    "PRVW_QST1" TEXT,
    "PRVW_1NAM" TEXT,
    "PRVW_1ADD1" TEXT,
    "PRVW_1ADD2" TEXT,
    "PRVW_1CITY" TEXT,
    "PRVW_1STATE" TEXT,
    "PRVW_1ZIP" TEXT,
    "PRVW_1CNT" TEXT,
    "PRVW_1TEL" TEXT,
    "PRVW_1TIT" TEXT,
    "PRVW_1SUPN" TEXT,
    "PRVW_1SUPG" TEXT,
    "PRVW_1SRTDT" DATE,
    "PRVW_1SRTEND" DATE,
    "PRVW_1DUT" TEXT,
    "PRVW_2NAM" TEXT,
    "PRVW_2ADD1" TEXT,
    "PRVW_2ADD2" TEXT,
    "PRVW_2CITY" TEXT,
    "PRVW_2STATE" TEXT,
    "PRVW_2ZIP" TEXT,
    "PRVW_2CNT" TEXT,
    "PRVW_2TEL" TEXT,
    "PRVW_2TIT" TEXT,
    "PRVW_2SUPN" TEXT,
    "PRVW_2SUPG" TEXT,
    "PRVW_2SRTDT" DATE,
    "PRVW_2SRTEND" DATE,
    "PRVW_2DUT" TEXT,
    "PRVW_QST2" TEXT,
    "PRVW_3NAM" TEXT,
    "PRVW_3ADD1" TEXT,
    "PRVW_3ADD2" TEXT,
    "PRVW_3CITY" TEXT,
    "PRVW_3STATE" TEXT,
    "PRVW_3ZIP" TEXT,
    "PRVW_3CNT" TEXT,
    "PRVW_3COUR" TEXT,
    "PRVW_3FROM" DATE,
    "PRVW_3TO" DATE,
    "PRVW_4NAM" TEXT,
    "PRVW_4ADD1" TEXT,
    "PRVW_4ADD2" TEXT,
    "PRVW_4CITY" TEXT,
    "PRVW_4STATE" TEXT,
    "PRVW_4ZIP" TEXT,
    "PRVW_4CNT" TEXT,
    "PRVW_4COUR" TEXT,
    "PRVW_4FROM" DATE,
    "PRVW_4TO" DATE,

    CONSTRAINT "PREV_WORK_pkey" PRIMARY KEY ("ID_PREV_WORK")
);

-- CreateTable
CREATE TABLE "public"."ADD_WORK" (
    "ID_ADD_WORK" BIGSERIAL NOT NULL,
    "ID_CLIENT" BIGINT,
    "AW_TRIB" TEXT,
    "AW_NAME" TEXT,
    "AW_LANG" TEXT,
    "AW_CNT" TEXT,
    "AW_" TEXT,
    "AW_CHAR" TEXT,
    "AW_CNAME" TEXT,
    "AW_QST1" TEXT,
    "AW_ANS1" TEXT,
    "AW_QST2" TEXT,
    "AW_2CNT" TEXT,
    "AW_2BRA" TEXT,
    "AW_2RANK" TEXT,
    "AW_2SPEC" TEXT,
    "AW_2FROM" DATE,
    "AW_2TO" DATE,
    "AW_2MEMB" TEXT,
    "AW_2EXP" TEXT,

    CONSTRAINT "ADD_WORK_pkey" PRIMARY KEY ("ID_ADD_WORK")
);

-- CreateTable
CREATE TABLE "public"."SECURITY" (
    "ID_SECURITY" BIGSERIAL NOT NULL,
    "ID_CLIENT" BIGINT,
    "SEC_QST1" TEXT,
    "SEC_ANS1" TEXT,
    "SEC_QST2" TEXT,
    "SEC_ANS2" TEXT,
    "SEC_QST3" TEXT,
    "SEC_ANS3" TEXT,
    "SEC_QST4" TEXT,
    "SEC_ANS4" TEXT,
    "SEC_QST5" TEXT,
    "SEC_ANS5" TEXT,
    "SEC_QST6" TEXT,
    "SEC_ANS6" TEXT,
    "SEC_QST7" TEXT,
    "SEC_ANS7" TEXT,
    "SEC_QST8" TEXT,
    "SEC_ANS8" TEXT,
    "SEC_QST9" TEXT,
    "SEC_ANS9" TEXT,
    "SEC_QST10" TEXT,
    "SEC_ANS10" TEXT,
    "SEC_QST11" TEXT,
    "SEC_ANS11" TEXT,
    "SEC_QST12" TEXT,
    "SEC_ANS12" TEXT,
    "SEC_QST13" TEXT,
    "SEC_ANS13" TEXT,
    "SEC_QST14" TEXT,
    "SEC_ANS14" TEXT,
    "SEC_QST15" TEXT,
    "SEC_ANS15" TEXT,
    "SEC_QST16" TEXT,
    "SEC_ANS16" TEXT,
    "SEC_QST17" TEXT,
    "SEC_ANS17" TEXT,
    "SEC_QST18" TEXT,
    "SEC_ANS18" TEXT,
    "SEC_QST19" TEXT,
    "SEC_ANS19" TEXT,
    "SEC_QST20" TEXT,
    "SEC_ANS20" TEXT,
    "SEC_QST21" TEXT,
    "SEC_ANS21" TEXT,
    "SEC_QST22" TEXT,
    "SEC_ANS22" TEXT,
    "SEC_QST23" TEXT,
    "SEC_ANS23" TEXT,
    "SEC_QST24" TEXT,
    "SEC_ANS24" TEXT,
    "SEC_QST25" TEXT,
    "SEC_ANS25" TEXT,
    "SEC_QST26" TEXT,
    "SEC_ANS26" TEXT,
    "SEC_QST27" TEXT,
    "SEC_ANS27" TEXT,
    "SEC_QST28" TEXT,
    "SEC_ANS28" TEXT,
    "SEC_QST29" TEXT,
    "SEC_ANS29" TEXT,
    "SEC_QST30" TEXT,
    "SEC_ANS30" TEXT,
    "SEC_QST31" TEXT,
    "SEC_ANS31" TEXT,
    "SEC_QST32" TEXT,
    "SEC_ANS32" TEXT,

    CONSTRAINT "SECURITY_pkey" PRIMARY KEY ("ID_SECURITY")
);

-- AddForeignKey
ALTER TABLE "public"."TRAVEL_INFO" ADD CONSTRAINT "TRAVEL_INFO_ID_CLIENT_fkey" FOREIGN KEY ("ID_CLIENT") REFERENCES "public"."CLIENTS"("ID_CLIENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ADDRESS" ADD CONSTRAINT "ADDRESS_ID_CLIENT_fkey" FOREIGN KEY ("ID_CLIENT") REFERENCES "public"."CLIENTS"("ID_CLIENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PASSPORT" ADD CONSTRAINT "PASSPORT_ID_CLIENT_fkey" FOREIGN KEY ("ID_CLIENT") REFERENCES "public"."CLIENTS"("ID_CLIENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."FAMILY" ADD CONSTRAINT "FAMILY_ID_CLIENT_fkey" FOREIGN KEY ("ID_CLIENT") REFERENCES "public"."CLIENTS"("ID_CLIENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PRESS_WORK" ADD CONSTRAINT "PRESS_WORK_ID_CLIENT_fkey" FOREIGN KEY ("ID_CLIENT") REFERENCES "public"."CLIENTS"("ID_CLIENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PREV_WORK" ADD CONSTRAINT "PREV_WORK_ID_CLIENT_fkey" FOREIGN KEY ("ID_CLIENT") REFERENCES "public"."CLIENTS"("ID_CLIENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ADD_WORK" ADD CONSTRAINT "ADD_WORK_ID_CLIENT_fkey" FOREIGN KEY ("ID_CLIENT") REFERENCES "public"."CLIENTS"("ID_CLIENT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."SECURITY" ADD CONSTRAINT "SECURITY_ID_CLIENT_fkey" FOREIGN KEY ("ID_CLIENT") REFERENCES "public"."CLIENTS"("ID_CLIENT") ON DELETE SET NULL ON UPDATE CASCADE;
